name: Build DEB

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm lld build-essential fakeroot git curl unzip
    
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        
    - name: Download SDK
      run: |
        mkdir -p $HOME/theos/sdks
        cd $HOME/theos/sdks
        curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
        unzip -q master.zip
        mv sdks-master/* ./
        rm -rf sdks-master master.zip
        
    - name: Build Package
      env:
        THEOS: ${{ github.workspace }}/../theos
      run: |
        export THEOS=$HOME/theos
        export PATH="/usr/bin:$PATH"
        cd ${{ github.workspace }}
        make clean
        make package FINALPACKAGE=1 CC=clang CXX=clang++ LD=ld.lld
        
    - name: Upload DEB
      uses: actions/upload-artifact@v4
      with:
        name: QuickTranslate-hombergerkurde
        path: packages/*.deb
